name: Android App Build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: [self-hosted, default]

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "yarn"

      # Install Yarn globally so the `yarn` executable is on PATH
      - name: Install Yarn globally
        run: |
          # npm v9+/10 supports --location=global to avoid permission issues on some setups
          npm install -g yarn --location=global
          yarn --version

      # Install EAS CLI (used by eas build)
      - name: Install eas-cli
        run: |
          npm install -g eas-cli --location=global
          eas --version || echo "eas not found"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Show versions (debug)
        run: |
          echo "PATH: $PATH"
          node --version
          npm --version
          yarn --version
          eas --version || echo "eas not available"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Android app
        run: eas build --platform android --profile production --local --output ${{ github.workspace }}/app-release.aab

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ github.workspace }}/app-release.aab
